#!/usr/bin/env bash
#set -x

BASE_URL=http://localhost:8080

function retrieveRooms {
	echo
	echo Retrieving rooms...
	curl -s $BASE_URL/rooms | jq .
}

retrieveRooms

echo
echo Creating rooms...
curl -s -X POST $BASE_URL/rooms -H "Content-Type: application/json" -d '{"name": "Room 1", "location": "Floor 5"}' | jq .
curl -s -X POST $BASE_URL/rooms -H "Content-Type: application/json" -d '{"name": "Room 2"}' | jq .
curl -s -X POST $BASE_URL/rooms -H "Content-Type: application/json" -d '{"name": "Room 3"}' | jq .
curl -s -X POST $BASE_URL/rooms -H "Content-Type: application/json" -d '{"name": "Room 4", "location": "Floor 6"}' | jq .

retrieveRooms

echo
echo Retrieving room 1...
curl -s $BASE_URL/rooms/1

echo
echo Retrieving room 2...
curl -s $BASE_URL/rooms/2

echo
echo Deleting rooms 1-3...
curl -s -X DELETE $BASE_URL/rooms/1
echo
curl -s -X DELETE $BASE_URL/rooms/2
echo
curl -s -X DELETE $BASE_URL/rooms/3

retrieveRooms

echo
echo Retrieving room 100000...
curl -v $BASE_URL/rooms/10000

echo
echo Retrieving bookings...
curl -s $BASE_URL/bookings | jq .

echo
echo Creating booking...
curl -s -X POST $BASE_URL/bookings -H "Content-Type: application/json" -d '{"roomId": 4, "userName" : "user1", "startDateTime": "2025-10-01T10:00:00Z", "endDateTime": "2025-10-01T12:00:00Z"}'

echo
echo Retrieving bookings...
curl -s $BASE_URL/bookings | jq .

